import {open,shot,flush,BASE} from '../common/harness.mjs';
import {fill,clickBtn,toast,dlgText} from './d_lib.mjs';
const {browser,page}=await open({height:1600,slow:true});
const log=(...a)=>console.log(...a);
await page.goto(BASE+'/payroll',{waitUntil:'networkidle'}); await page.waitForTimeout(800);
await page.getByRole('tab',{name:/Сүүл цалин/}).click().catch(()=>{}); await page.waitForTimeout(600);
log('final tab',(await page.locator('main').innerText()).replace(/\n+/g,' | ').slice(600,1400));
await clickBtn(page,'^GL ноорог журнал үүсгэх$'); await page.waitForTimeout(1200);
log('dlg',await dlgText(page)); const d=page.locator('[role=dialog],[role=alertdialog]').last(); const names=await d.locator('button').allInnerTexts().catch(()=>[]); const bi=names.findIndex(x=>x.trim()==='Болих'); if(bi>=0) await d.locator('button').nth(bi+1).click();
log('toast',await toast(page,15000)); await shot(page,'d-payroll-3'); flush(); await browser.close();
