// Авлага / өглөгийн баримт — lib/actions/arap.ts. docs/dev/arap.md.
// Төрлөөс хамаарах шийдвэр ЗӨВХӨН lib/arap/document-kind.ts (модуль ar|ap).

import { defineObject } from "../define";

export const arapDocument = defineObject({
  key: "arap_document",
  label: "Нэхэмжлэх / кредит нэхэмжлэл",
  layer: "core",
  module: "ar|ap",
  table: "ar_ap_documents",
  statusColumn: "status",
  states: {
    draft: { label: "Ноорог", ledger: "none", editable: true },
    posted: { label: "Батлагдсан", ledger: "posted" },
    partially_paid: { label: "Хэсэгчлэн төлсөн", ledger: "posted" },
    paid: { label: "Төлөгдсөн", ledger: "posted" },
    reversed: { label: "Буцаагдсан", ledger: "reversed", terminal: true },
  },
  initial: ["draft", "posted"],
  transitions: [
    {
      action: "create",
      from: [],
      to: "draft",
      permission: { module: "ar|ap", level: "write" },
      guards: ["period_open"],
      tool: {
        name: "create_arap_invoice",
        aliases: ["create_arap_invoices_batch", "create_credit_note", "create_ap_invoice_from_po"],
      },
      note: "«Шууд бичих» горимд хязгаар доторх баримт шууд «posted» (журналтай) үүснэ.",
    },
    {
      action: "update",
      from: ["draft"],
      to: "draft",
      permission: { module: "ar|ap", level: "write" },
      guards: ["period_open"],
      tool: { name: "update_arap_document" },
      note: "Зөвхөн ноорог — батлагдсаныг буцаагаад шинээр бүртгэнэ.",
    },
    {
      action: "post",
      from: ["draft"],
      to: "posted",
      permission: { module: "ar|ap", level: "post" },
      guards: ["period_open", "not_future_period", "ai_post_mode", "ai_post_limit"],
      effects: ["journal", "voucher_no", "hook:beforeJournalPost"],
      tool: { name: "post_arap_document", aliases: ["post_arap_documents_batch"] },
    },
    {
      action: "settle",
      from: ["posted", "partially_paid"],
      to: "partially_paid",
      permission: { module: "ar|ap", level: "post" },
      guards: ["period_open"],
      tool: { name: "pay_arap_document", aliases: ["settle_arap_offset", "apply_advance_to_invoice"] },
      note: "Төлөв ДЕРИВАТ — paidAmount-аас бодогдоно: бүтэн төлөгдвөл «paid», төлөлт буцвал буцна. Кассын баримт / суутгал / урьдчилгаагаар.",
    },
    {
      action: "settle_full",
      from: ["posted", "partially_paid"],
      to: "paid",
      permission: { module: "ar|ap", level: "post" },
      guards: ["period_open"],
      tool: { name: "pay_arap_document", aliases: ["settle_arap_offset", "apply_advance_to_invoice", "write_off_arap_document"] },
      note: "Үлдэгдэл 0 болмогц «paid» (найдваргүй авлагын хасалт ч мөн). Төлөлтийн баримт буцаагдвал/устгагдвал өмнөх төлөвт буцна.",
    },
    {
      action: "unsettle",
      from: ["partially_paid", "paid"],
      to: "posted",
      permission: { module: "ar|ap", level: "post" },
      guards: ["period_open"],
      actor: "system",
      note: "Төлөлтийн кассын баримт / суутгал буцаагдах эсвэл устгагдахад paidAmount-аас дахин бодогдоно.",
    },
    {
      action: "reverse",
      from: ["posted"],
      to: "reversed",
      permission: { module: "ar|ap", level: "post" },
      guards: ["period_open", "no_open_settlements", "not_source_locked"],
      effects: ["journal", "voucher_no"],
      note: "Вэбийн «Буцаах» (MCP tool алга). Хэсэгчилсэн буцаалт = кредит нэхэмжлэл (create_credit_note). Кредит баримт төлөгдсөн төлөвөөс ч буцаагдана.",
    },
    {
      action: "delete",
      from: ["draft", "posted"],
      to: null,
      permission: { module: "ar|ap", level: "post" },
      guards: ["period_open", "no_open_settlements", "not_source_locked", "ebarimt_not_sent", "ai_post_mode", "ai_post_limit"],
      effects: ["journal"],
      tool: { name: "delete_arap_document" },
      note: "Ноорог — write эрхээр, аль ч горимд. Батлагдсан нэхэмжлэх GL журналтайгаа устна (product owner 2026-10-01, аудит үлдэнэ); кредит баримт, POS-оос үүссэн, eBarimt-д бүртгэгдсэн, төлөлттэй бол ҮГҮЙ.",
    },
  ],
  relations: [
    { name: "counterparty", targetTable: "counterparties", column: "counterparty_id", kind: "fk", cardinality: "one" },
    { name: "voucher", targetTable: "journal_vouchers", column: "voucher_id", kind: "fk", cardinality: "one" },
    { name: "reversalVoucher", targetTable: "journal_vouchers", column: "reversal_voucher_id", kind: "fk", cardinality: "one" },
    { name: "purchaseOrder", targetTable: "purchase_orders", column: "purchase_order_id", kind: "fk", cardinality: "one" },
    { name: "sourceDocument", targetTable: "ar_ap_documents", column: "source_document_id", kind: "fk", cardinality: "one" },
    { name: "posSale", targetTable: "pos_sales", column: "source_id", kind: "polymorphic", cardinality: "one" },
    { name: "lines", targetTable: "ar_ap_document_lines", column: "document_id", kind: "fk", cardinality: "many" },
    { name: "settlements", targetTable: "ar_ap_settlements", column: "document_id", kind: "fk", cardinality: "many" },
  ],
  idempotency: { column: "external_ref", prefixes: ["recurring:"] },
  invariants: ["V05", "V08", "V09"],
  note: "Буцаалт = тусдаа баримт (кредит нэхэмжлэл / дебит нэхэмжлэх, дүн эерэг), журнал нь улаан сторно. Сөрөг мөртэй нэхэмжлэх ХЭРЭГЛЭХГҮЙ.",
});
