// Мөнгөн хөрөнгийн баримт (касс / банк) — lib/actions/cash.ts. docs/dev/cash.md.

import { defineObject } from "../define";

export const cashDocument = defineObject({
  key: "cash_document",
  label: "Мөнгөн хөрөнгийн баримт",
  layer: "core",
  module: "cash",
  table: "cash_documents",
  statusColumn: "status",
  states: {
    draft: { label: "Ноорог", ledger: "none", editable: true },
    posted: { label: "Батлагдсан", ledger: "posted" },
    reversed: { label: "Буцаагдсан", ledger: "reversed", terminal: true },
  },
  initial: ["draft", "posted"],
  transitions: [
    {
      action: "create",
      from: [],
      to: "draft",
      permission: { module: "cash", level: "write" },
      guards: ["period_open"],
      tool: { name: "create_cash_transaction", aliases: ["create_cash_transactions_batch", "import_bank_statement"] },
      note: "Төрөл receipt | payment | transfer. «Шууд бичих» горимд хязгаар дотор шууд «posted»; нэхэмжлэх төлөх бол pay_arap_document.",
    },
    {
      action: "update",
      from: ["draft"],
      to: "draft",
      permission: { module: "cash", level: "write" },
      guards: ["period_open"],
      tool: { name: "update_cash_document" },
      note: "Зөвхөн ноорог — батлагдсаныг буцаалтаар засна.",
    },
    {
      action: "post",
      from: ["draft"],
      to: "posted",
      permission: { module: "cash", level: "post" },
      guards: ["period_open", "not_future_period", "control_account", "ai_post_mode", "ai_post_limit"],
      effects: ["journal", "voucher_no", "hook:beforeJournalPost"],
      tool: { name: "post_cash_document", aliases: ["post_cash_documents_batch"] },
      note: "Нэхэмжлэхгүй баримтын харьцах данс АР/АП-ийн хяналтын данс бол control_account_guard (warn | block).",
    },
    {
      action: "reverse",
      from: ["posted"],
      to: "reversed",
      permission: { module: "cash", level: "post" },
      guards: ["period_open", "not_source_locked", "ai_post_mode", "ai_post_limit"],
      effects: ["journal", "voucher_no"],
      tool: { name: "reverse_cash_document" },
      note: "Улаан сторно; нэхэмжлэхийн төлөлт байсан бол үлдэгдэл нь сэргэнэ.",
    },
    {
      action: "delete",
      from: ["draft", "posted"],
      to: null,
      permission: { module: "cash", level: "post" },
      guards: ["period_open", "not_source_locked", "ai_post_mode", "ai_post_limit"],
      effects: ["journal"],
      tool: { name: "delete_cash_document" },
      note: "Ноорог — write эрхээр, аль ч горимд. Батлагдсан баримт GL журналтайгаа устна (тайлант үе нээлттэй, аудит үлдэнэ); POS-оос үүссэн, QPay-ийн төлбөрийн баримт бол ҮГҮЙ.",
    },
  ],
  relations: [
    { name: "fromCashAccount", targetTable: "cash_accounts", column: "from_cash_account_id", kind: "fk", cardinality: "one" },
    { name: "toCashAccount", targetTable: "cash_accounts", column: "to_cash_account_id", kind: "fk", cardinality: "one" },
    { name: "counterparty", targetTable: "counterparties", column: "counterparty_id", kind: "fk", cardinality: "one" },
    { name: "voucher", targetTable: "journal_vouchers", column: "voucher_id", kind: "fk", cardinality: "one" },
    { name: "reversalVoucher", targetTable: "journal_vouchers", column: "reversal_voucher_id", kind: "fk", cardinality: "one" },
    { name: "sourceVoucher", targetTable: "journal_vouchers", column: "source_voucher_id", kind: "fk", cardinality: "one" },
    { name: "arapDocument", targetTable: "ar_ap_documents", column: "ar_ap_document_id", kind: "fk", cardinality: "one" },
    { name: "settlements", targetTable: "ar_ap_settlements", column: "cash_document_id", kind: "fk", cardinality: "many" },
  ],
  idempotency: { column: "external_ref" },
  invariants: ["V05", "V06"],
});
