-- ШИЛЖСЭН (2026-10-01): журналын DB хамгаалалтыг гараар ажиллуулахгүй.
-- Эх: scripts/lib/ledger-invariants.mjs — deploy бүрд `db:predeploy` нь
-- `drizzle-kit push`-ийн ДАРАА `node scripts/apply-ledger-invariants.mjs`-ээр
-- идемпотентоор тавина (docs/dev/gl.md §2c). Гараар тавьдаг байсан тул
-- SmartGPS DB-д огт байгаагүй, SaaS-ийн Дт/Кт CHECK-ийг push устгадаг байв.
-- Анхны агуулга git түүхэд (энэ файлын 2026-08-19-ний хувилбар).
--
-- Ганцаар тавих шаардлагатай бол:  node scripts/apply-ledger-invariants.mjs
